In [1]:
#Importing some important libraries 
import numpy as np 
import pandas as pd
#important libraries to habdle catigerocal data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
#libraries to handle splitting 
from sklearn.model_selection import train_test_split
#libraries to handle feature scaling 
from sklearn.preprocessing import StandardScaler
# DL libraries
from tensorflow.keras.models import Sequential  
from tensorflow.keras.layers import Dense

In [2]:
#Reading dataset
df = pd.read_csv('bank.csv')

In [3]:
df.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [4]:
#checking for missing data if there is any and how many 
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [6]:
#Splitting data into inputs as x and outputs as y
x = df.iloc[:, :16].values
y = df.iloc[:, -1:].values

In [7]:
#then we check the input rows and coulmns shape
x.shape

(11162, 16)

In [8]:
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [9]:
y.shape

(11162, 1)

In [10]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [11]:
# Handling categorical data
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,10,15])],remainder = "passthrough")
x = ct.fit_transform(x)

In [12]:
# as we see the categorical data converted to binary
x

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [0.0, 0.0, 0.0, ..., 2, 172, 5],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [13]:
ct2 = ColumnTransformer([('one', OneHotEncoder(), [0])], remainder = 'passthrough')
y = ct2.fit_transform(y)

In [14]:
#as we see the yes and no data converted to 0 and 1
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [15]:
# Splitting data to train sets and test sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [16]:
x_train

array([[0.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 1.0, 0.0, ..., 5, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 8, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [17]:
y_train

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [18]:
print('Inputs shape ', x.shape)
print('Outputs shape ', y.shape)
print('x_train shape ', x_train.shape)
print('x_test shape ', x_test.shape)
print('y_train shape ', y_train.shape)
print('y_test shape', y_test.shape)

Inputs shape  (11162, 51)
Outputs shape  (11162, 2)
x_train shape  (8929, 51)
x_test shape  (2233, 51)
y_train shape  (8929, 2)
y_test shape (2233, 2)


In [19]:
#feature scaling 
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [20]:
# as we see compare to the previous x_train data the values has been scaled to similar unified range
x_train

array([[-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192,  2.18530314, -0.17658264, ...,  0.92827075,
        -0.48428507, -0.35888264],
       ...,
       [-0.37172192, -0.45760242, -0.17658264, ...,  2.04743488,
        -0.48428507, -0.35888264],
       [ 2.69018306, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.56394809,
        -0.48428507, -0.35888264]])

In [21]:
#same scaling feature thing goes for x_text data value
x_test

array([[-0.35506564, -0.46571851, -0.16329932, ..., -0.51893725,
         2.62409874,  0.62465525],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.51893725,
         1.30248101,  1.63872661],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612],
       ...,
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612],
       [ 2.81638066, -0.46571851, -0.16329932, ..., -0.51893725,
        -0.46885387, -0.38941612],
       [-0.35506564, -0.46571851, -0.16329932, ..., -0.17189116,
        -0.46885387, -0.38941612]])

In [22]:
# now we do the deep learning ann modeling
ob = Sequential()
ob.add(Dense(units = 50, kernel_initializer = 'random_uniform', activation = 'relu'))# Input layer
ob.add(Dense(units = 100, kernel_initializer = 'random_uniform', activation = 'relu'))# Hidden layer 1 
ob.add(Dense(units = 100, kernel_initializer = 'random_uniform', activation = 'relu'))# Hidden layer 2
ob.add(Dense(units = 2, kernel_initializer = 'random_uniform', activation = 'softmax'))# Output layer 
ob.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])# Compiling model 
ob.fit(x_train, y_train, epochs = 100)# Training the model 

Epoch 1/100
280/280 [==============================] - 1s 879us/step - loss: 0.4386 - accuracy: 0.7928
Epoch 2/100
280/280 [==============================] - 0s 825us/step - loss: 0.3591 - accuracy: 0.8475
Epoch 3/100
280/280 [==============================] - 0s 859us/step - loss: 0.3464 - accuracy: 0.8540
Epoch 4/100
280/280 [==============================] - 0s 854us/step - loss: 0.3342 - accuracy: 0.8586
Epoch 5/100
280/280 [==============================] - 0s 808us/step - loss: 0.3322 - accuracy: 0.8606
Epoch 6/100
280/280 [==============================] - 0s 814us/step - loss: 0.3198 - accuracy: 0.8671
Epoch 7/100
280/280 [==============================] - 0s 901us/step - loss: 0.3109 - accuracy: 0.8717
Epoch 8/100
280/280 [==============================] - 0s 908us/step - loss: 0.3133 - accuracy: 0.8678
Epoch 9/100
280/280 [==============================] - 0s 804us/step - loss: 0.3009 - accuracy: 0.8761
Epoch 10/100
280/280 [==============================] - 0s 796us/step - l

280/280 [==============================] - 0s 823us/step - loss: 0.0479 - accuracy: 0.9833
Epoch 80/100
280/280 [==============================] - 0s 802us/step - loss: 0.0764 - accuracy: 0.9736
Epoch 81/100
280/280 [==============================] - 0s 768us/step - loss: 0.0683 - accuracy: 0.9748
Epoch 82/100
280/280 [==============================] - 0s 772us/step - loss: 0.0464 - accuracy: 0.9830
Epoch 83/100
280/280 [==============================] - 0s 789us/step - loss: 0.0352 - accuracy: 0.9871
Epoch 84/100
280/280 [==============================] - 0s 776us/step - loss: 0.0325 - accuracy: 0.9881
Epoch 85/100
280/280 [==============================] - 0s 757us/step - loss: 0.0340 - accuracy: 0.9878
Epoch 86/100
280/280 [==============================] - 0s 828us/step - loss: 0.0588 - accuracy: 0.9784
Epoch 87/100
280/280 [==============================] - 0s 788us/step - loss: 0.0780 - accuracy: 0.9696
Epoch 88/100
280/280 [==============================] - 0s 782us/step - loss:

In [23]:
ypred = ob.predict(x_test)
ypred

array([[1.0000000e+00, 9.1965632e-23],
       [3.5886452e-15, 1.0000000e+00],
       [1.0000000e+00, 6.8453629e-17],
       ...,
       [6.1810006e-06, 9.9999380e-01],
       [1.0000000e+00, 3.8671455e-14],
       [1.0000000e+00, 5.4586826e-13]], dtype=float32)

In [24]:
df.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes