In [1]:
#Importing the libraries 
import numpy as np
import pandas as pd
import sklearn.metrics as mse
# Importing libraries to handle categorical data 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
# Importing libraries to split into train and test sets 
from sklearn.model_selection import train_test_split
#Importing libraries to handle feature scaling 
from sklearn.preprocessing import StandardScaler

In [7]:
df = pd.read_csv("50_Startups.csv")
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
#checking for missing data if there is any and how many 
df.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    1
State              0
Profit             0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   49 non-null     float64
 2   Marketing Spend  49 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [9]:
#since we got some missing values we need to handle them so we need to do following
# Replace missing values  with the mean (because data is numerical)
df['Administration'].fillna(df['Administration'].mean(), inplace = True)
df['Marketing Spend'].fillna(df['Marketing Spend'].mean(), inplace = True)

In [12]:
# so as we see now the dataset has zero missing value so we can proceed
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [19]:
#Splitting data into inputs as x and outputs as y
x = df.iloc[:, 0:4]
x.head()

R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [20]:
y = df.iloc[:, -1:].values
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

In [21]:
#Handling categorical data and convert them into binary
ct = ColumnTransformer([('one', OneHotEncoder(), [3])], remainder = 'passthrough')
x = ct.fit_transform(x)

In [22]:
df["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [23]:
x

array([[0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.65349200e+05,
        1.36897800e+05, 4.71784100e+05],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.62597700e+05,
        1.51377590e+05, 4.43898530e+05],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.53441510e+05,
        1.01145550e+05, 4.07934540e+05],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.44372410e+05,
        1.18671850e+05, 3.83199620e+05],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.42107340e+05,
        9.13917700e+04, 3.66168420e+05],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.31876900e+05,
        9.98147100e+04, 3.62861360e+05],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.34615460e+05,
        1.47198870e+05, 2.12725267e+05],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.30298130e+05,
        1.45530060e+05, 3.23876680e+05],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.20542520e+05,
        1.48718950e+05, 

In [24]:
# Splitting data to train sets and test sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [25]:
print('Inputs shape ', x.shape)
print('Outputs shape ', y.shape)
print('x_train shape ', x_train.shape)
print('x_test shape ', x_test.shape)
print('y_train shape ', y_train.shape)
print('y_test shape', y_test.shape)

Inputs shape  (50, 6)
Outputs shape  (50, 1)
x_train shape  (40, 6)
x_test shape  (10, 6)
y_train shape  (40, 1)
y_test shape (10, 1)


In [26]:
#feature scaling 
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [27]:
# DL libraries
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

In [29]:
ob=Sequential()
ob.add(Dense(units=6,kernel_initializer= "random_uniform",activation= "relu"))# Input layer
ob.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))# Hidden layer 1
ob.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))# Hidden layer 2 
ob.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))# Hidden layer 3 
ob.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))# Hidden layer 4 
ob.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))# Hidden layer 5
ob.add(Dense(units=1,kernel_initializer= "random_uniform",activation= "relu"))#  Output layer 
ob.compile(optimizer="rmsprop",loss="mean_squared_error")# Compiling model 

In [30]:
ob.fit(x_train, y_train, epochs = 1000)# Training the model 

Epoch 1/1000
2/2 [==============================] - 3s 7ms/step - loss: 13615994880.0000
Epoch 2/1000
2/2 [==============================] - 0s 9ms/step - loss: 13615994880.0000
Epoch 3/1000
2/2 [==============================] - 0s 11ms/step - loss: 13615991808.0000
Epoch 4/1000
2/2 [==============================] - 0s 9ms/step - loss: 13615991808.0000
Epoch 5/1000
2/2 [==============================] - 0s 7ms/step - loss: 13615990784.0000
Epoch 6/1000
2/2 [==============================] - 0s 6ms/step - loss: 13615989760.0000
Epoch 7/1000
2/2 [==============================] - 0s 7ms/step - loss: 13615988736.0000
Epoch 8/1000
2/2 [==============================] - 0s 6ms/step - loss: 13615988736.0000
Epoch 9/1000
2/2 [==============================] - 0s 7ms/step - loss: 13615986688.0000
Epoch 10/1000
2/2 [==============================] - 0s 10ms/step - loss: 13615985664.0000
Epoch 11/1000
2/2 [==============================] - 0s 11ms/step - loss: 13615985664.0000
Epoch 12/1000
2/

2/2 [==============================] - 0s 5ms/step - loss: 13611969536.0000
Epoch 93/1000
2/2 [==============================] - 0s 5ms/step - loss: 13611742208.0000
Epoch 94/1000
2/2 [==============================] - 0s 4ms/step - loss: 13611491328.0000
Epoch 95/1000
2/2 [==============================] - 0s 5ms/step - loss: 13611214848.0000
Epoch 96/1000
2/2 [==============================] - 0s 5ms/step - loss: 13610923008.0000
Epoch 97/1000
2/2 [==============================] - 0s 5ms/step - loss: 13610614784.0000
Epoch 98/1000
2/2 [==============================] - 0s 4ms/step - loss: 13610354688.0000
Epoch 99/1000
2/2 [==============================] - 0s 4ms/step - loss: 13610096640.0000
Epoch 100/1000
2/2 [==============================] - 0s 4ms/step - loss: 13609808896.0000
Epoch 101/1000
2/2 [==============================] - 0s 5ms/step - loss: 13609498624.0000
Epoch 102/1000
2/2 [==============================] - 0s 4ms/step - loss: 13609183232.0000
Epoch 103/1000
2/2 [=

2/2 [==============================] - 0s 6ms/step - loss: 13448717312.0000
Epoch 183/1000
2/2 [==============================] - 0s 8ms/step - loss: 13443478528.0000
Epoch 184/1000
2/2 [==============================] - 0s 5ms/step - loss: 13438822400.0000
Epoch 185/1000
2/2 [==============================] - 0s 5ms/step - loss: 13433235456.0000
Epoch 186/1000
2/2 [==============================] - 0s 7ms/step - loss: 13427946496.0000
Epoch 187/1000
2/2 [==============================] - 0s 5ms/step - loss: 13421897728.0000
Epoch 188/1000
2/2 [==============================] - 0s 5ms/step - loss: 13415460864.0000
Epoch 189/1000
2/2 [==============================] - 0s 5ms/step - loss: 13408289792.0000
Epoch 190/1000
2/2 [==============================] - 0s 6ms/step - loss: 13400856576.0000
Epoch 191/1000
2/2 [==============================] - 0s 5ms/step - loss: 13393422336.0000
Epoch 192/1000
2/2 [==============================] - 0s 6ms/step - loss: 13386989568.0000
Epoch 193/1000

2/2 [==============================] - 0s 5ms/step - loss: 11907248128.0000
Epoch 273/1000
2/2 [==============================] - 0s 3ms/step - loss: 11867102208.0000
Epoch 274/1000
2/2 [==============================] - 0s 5ms/step - loss: 11835183104.0000
Epoch 275/1000
2/2 [==============================] - 0s 3ms/step - loss: 11797223424.0000
Epoch 276/1000
2/2 [==============================] - 0s 4ms/step - loss: 11759052800.0000
Epoch 277/1000
2/2 [==============================] - 0s 4ms/step - loss: 11718054912.0000
Epoch 278/1000
2/2 [==============================] - 0s 3ms/step - loss: 11682204672.0000
Epoch 279/1000
2/2 [==============================] - ETA: 0s - loss: 11222977536.000 - 0s 4ms/step - loss: 11644340224.0000
Epoch 280/1000
2/2 [==============================] - 0s 3ms/step - loss: 11598893056.0000
Epoch 281/1000
2/2 [==============================] - 0s 5ms/step - loss: 11558851584.0000
Epoch 282/1000
2/2 [==============================] - 0s 4ms/step - los

2/2 [==============================] - 0s 3ms/step - loss: 5840921600.0000
Epoch 363/1000
2/2 [==============================] - 0s 3ms/step - loss: 5751720960.0000
Epoch 364/1000
2/2 [==============================] - 0s 2ms/step - loss: 5662531584.0000
Epoch 365/1000
2/2 [==============================] - 0s 3ms/step - loss: 5575777280.0000
Epoch 366/1000
2/2 [==============================] - 0s 3ms/step - loss: 5483136000.0000
Epoch 367/1000
2/2 [==============================] - 0s 3ms/step - loss: 5396489728.0000
Epoch 368/1000
2/2 [==============================] - 0s 3ms/step - loss: 5296363008.0000
Epoch 369/1000
2/2 [==============================] - 0s 3ms/step - loss: 5202428928.0000
Epoch 370/1000
2/2 [==============================] - 0s 2ms/step - loss: 5110797824.0000
Epoch 371/1000
2/2 [==============================] - 0s 4ms/step - loss: 5014298624.0000
Epoch 372/1000
2/2 [==============================] - 0s 3ms/step - loss: 4905220608.0000
Epoch 373/1000
2/2 [=====

2/2 [==============================] - 0s 7ms/step - loss: 1544167040.0000
Epoch 453/1000
2/2 [==============================] - 0s 7ms/step - loss: 1528821888.0000
Epoch 454/1000
2/2 [==============================] - 0s 7ms/step - loss: 1517592192.0000
Epoch 455/1000
2/2 [==============================] - 0s 7ms/step - loss: 1507162368.0000
Epoch 456/1000
2/2 [==============================] - 0s 8ms/step - loss: 1494845824.0000
Epoch 457/1000
2/2 [==============================] - 0s 8ms/step - loss: 1483072000.0000
Epoch 458/1000
2/2 [==============================] - 0s 8ms/step - loss: 1475798528.0000
Epoch 459/1000
2/2 [==============================] - 0s 7ms/step - loss: 1460878976.0000
Epoch 460/1000
2/2 [==============================] - 0s 9ms/step - loss: 1451569280.0000
Epoch 461/1000
2/2 [==============================] - 0s 6ms/step - loss: 1440907648.0000
Epoch 462/1000
2/2 [==============================] - 0s 9ms/step - loss: 1433352960.0000
Epoch 463/1000
2/2 [=====

2/2 [==============================] - 0s 4ms/step - loss: 663294848.0000
Epoch 544/1000
2/2 [==============================] - 0s 6ms/step - loss: 657782912.0000
Epoch 545/1000
2/2 [==============================] - 0s 5ms/step - loss: 651309952.0000
Epoch 546/1000
2/2 [==============================] - 0s 5ms/step - loss: 642850368.0000
Epoch 547/1000
2/2 [==============================] - 0s 6ms/step - loss: 635111296.0000
Epoch 548/1000
2/2 [==============================] - 0s 4ms/step - loss: 633532992.0000
Epoch 549/1000
2/2 [==============================] - 0s 5ms/step - loss: 627561600.0000
Epoch 550/1000
2/2 [==============================] - 0s 5ms/step - loss: 621351872.0000
Epoch 551/1000
2/2 [==============================] - 0s 4ms/step - loss: 612839232.0000
Epoch 552/1000
2/2 [==============================] - 0s 4ms/step - loss: 601989376.0000
Epoch 553/1000
2/2 [==============================] - 0s 6ms/step - loss: 592698304.0000
Epoch 554/1000
2/2 [================

2/2 [==============================] - 0s 6ms/step - loss: 266481104.0000
Epoch 636/1000
2/2 [==============================] - 0s 6ms/step - loss: 265920080.0000
Epoch 637/1000
2/2 [==============================] - 0s 6ms/step - loss: 263623648.0000
Epoch 638/1000
2/2 [==============================] - 0s 8ms/step - loss: 261573936.0000
Epoch 639/1000
2/2 [==============================] - 0s 7ms/step - loss: 258492896.0000
Epoch 640/1000
2/2 [==============================] - 0s 8ms/step - loss: 256161280.0000
Epoch 641/1000
2/2 [==============================] - 0s 8ms/step - loss: 254912944.0000
Epoch 642/1000
2/2 [==============================] - 0s 7ms/step - loss: 252187040.0000
Epoch 643/1000
2/2 [==============================] - 0s 7ms/step - loss: 250317616.0000
Epoch 644/1000
2/2 [==============================] - 0s 5ms/step - loss: 248037216.0000
Epoch 645/1000
2/2 [==============================] - 0s 8ms/step - loss: 247964672.0000
Epoch 646/1000
2/2 [================

2/2 [==============================] - 0s 6ms/step - loss: 159529824.0000
Epoch 728/1000
2/2 [==============================] - 0s 6ms/step - loss: 158685360.0000
Epoch 729/1000
2/2 [==============================] - 0s 6ms/step - loss: 158090912.0000
Epoch 730/1000
2/2 [==============================] - 0s 4ms/step - loss: 157139488.0000
Epoch 731/1000
2/2 [==============================] - 0s 4ms/step - loss: 156474368.0000
Epoch 732/1000
2/2 [==============================] - 0s 4ms/step - loss: 155814656.0000
Epoch 733/1000
2/2 [==============================] - 0s 5ms/step - loss: 154588640.0000
Epoch 734/1000
2/2 [==============================] - 0s 5ms/step - loss: 154017952.0000
Epoch 735/1000
2/2 [==============================] - 0s 6ms/step - loss: 153216592.0000
Epoch 736/1000
2/2 [==============================] - 0s 5ms/step - loss: 152464224.0000
Epoch 737/1000
2/2 [==============================] - 0s 5ms/step - loss: 151899840.0000
Epoch 738/1000
2/2 [================

2/2 [==============================] - 0s 5ms/step - loss: 113574992.0000
Epoch 820/1000
2/2 [==============================] - 0s 5ms/step - loss: 113381336.0000
Epoch 821/1000
2/2 [==============================] - 0s 5ms/step - loss: 114958160.0000
Epoch 822/1000
2/2 [==============================] - 0s 6ms/step - loss: 113634536.0000
Epoch 823/1000
2/2 [==============================] - 0s 5ms/step - loss: 112924368.0000
Epoch 824/1000
2/2 [==============================] - 0s 4ms/step - loss: 111964160.0000
Epoch 825/1000
2/2 [==============================] - 0s 6ms/step - loss: 112537776.0000
Epoch 826/1000
2/2 [==============================] - 0s 4ms/step - loss: 112671960.0000
Epoch 827/1000
2/2 [==============================] - 0s 5ms/step - loss: 112120472.0000
Epoch 828/1000
2/2 [==============================] - 0s 6ms/step - loss: 111228440.0000
Epoch 829/1000
2/2 [==============================] - ETA: 0s - loss: 119577728.000 - 0s 5ms/step - loss: 110349656.0000
Epoc

2/2 [==============================] - 0s 4ms/step - loss: 91280296.0000
Epoch 912/1000
2/2 [==============================] - 0s 3ms/step - loss: 92090328.0000
Epoch 913/1000
2/2 [==============================] - 0s 3ms/step - loss: 91447320.0000
Epoch 914/1000
2/2 [==============================] - 0s 3ms/step - loss: 91067960.0000
Epoch 915/1000
2/2 [==============================] - 0s 3ms/step - loss: 90531832.0000
Epoch 916/1000
2/2 [==============================] - 0s 3ms/step - loss: 90502056.0000
Epoch 917/1000
2/2 [==============================] - 0s 2ms/step - loss: 91087648.0000
Epoch 918/1000
2/2 [==============================] - 0s 3ms/step - loss: 90402736.0000
Epoch 919/1000
2/2 [==============================] - 0s 3ms/step - loss: 89612696.0000
Epoch 920/1000
2/2 [==============================] - 0s 3ms/step - loss: 90910832.0000
Epoch 921/1000
2/2 [==============================] - 0s 3ms/step - loss: 91372264.0000
Epoch 922/1000
2/2 [===========================

In [32]:
ypred = ob.predict(x_test)
ypred

array([[ 72438.86 ],
       [159400.61 ],
       [107963.28 ],
       [ 42153.027],
       [177377.44 ],
       [110932.836],
       [ 65676.4  ],
       [ 98597.96 ],
       [ 89947.664],
       [160679.89 ]], dtype=float32)

In [33]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])